import PDFDocument from "pdfkit";

export const generatePdf = async (data) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      info: {
        Author: "ElysiumAI",
        Title: data?.title || "Generated Document",
        Creator: "ElysiumAI",
      },
    });

    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject); // 👈 Fixed: properly reject promise on error

    // Title
    doc
      .fillColor("#111827") // 👈 Fixed: Set fillColor BEFORE calling .text()
      .fontSize(24)
      .text(data?.title || "Untitled Document", { align: "center" });

    // Subtitle
    if (data?.subtitle) {
      doc.moveDown(0.5);
      doc
        .fillColor("#6B7280")
        .fontSize(12)
        .text(data.subtitle, { align: "center" });
    }

    doc.moveDown(1.5);

    // Sections
    data?.sections?.forEach((s) => {
      // Section Heading
      doc
        .fillColor("#111827")
        .fontSize(16)
        .text(s.heading || "Section");

      doc.moveDown(0.4);

      // Section Points
      s?.points?.forEach((p) => {
        doc.fillColor("#374151").fontSize(11).text(`•  ${p}`, {
          lineGap: 4,
          paragraphGap: 4, // 👈 Clean bullet spacing instead of heavy moveDown()
        });
      });

      doc.moveDown(1);
    });

    doc.moveDown(1.5);

    // Footer
    doc
      .fillColor("#9CA3AF")
      .fontSize(10)
      .text("Generated by ElysiumAI", { align: "center" }); // 👈 Fixed: "center" as string

    doc.end();
  });
};
