import pptxgen from "pptxgenjs";

export const generatePpt = async (data) => {
  const pptx = new pptxgen();

  // 16:9 Widescreen Layout
  pptx.layout = "LAYOUT_16x9";
  pptx.author = "ElysiumAI";
  pptx.company = "ElysiumAI";
  pptx.title = data?.title || "Presentation";

  // Color Palette Theme
  const BG_COLOR = "0D0F14"; // Dark Navy background
  const ACCENT_COLOR = "6366F1"; // Indigo Accent
  const TEXT_MAIN = "F8FAFC"; // Clean White
  const TEXT_MUTED = "94A3B8"; // Slate Gray

  // -------------------------------------------------------------
  // 1. Title Slide (Cover)
  // -------------------------------------------------------------
  const coverSlide = pptx.addSlide();
  coverSlide.background = { color: BG_COLOR };

  // Decorative Accent Line
  coverSlide.addShape(pptx.shapes.RECTANGLE, {
    x: 0.8,
    y: 2.2,
    w: 0.1,
    h: 2.2,
    fill: { color: ACCENT_COLOR },
  });

  // Title Text
  coverSlide.addText(data?.title || "Presentation Title", {
    x: 1.1,
    y: 2.0,
    w: 11.0,
    h: 1.5,
    fontSize: 40,
    fontFace: "Arial",
    bold: true,
    color: TEXT_MAIN,
    valign: "middle",
  });

  // Subtitle Text
  if (data?.subtitle) {
    coverSlide.addText(data.subtitle, {
      x: 1.1,
      y: 3.5,
      w: 11.0,
      h: 0.8,
      fontSize: 20,
      fontFace: "Arial",
      color: TEXT_MUTED,
      valign: "top",
    });
  }

  // -------------------------------------------------------------
  // 2. Content Slides
  // -------------------------------------------------------------
  if (Array.isArray(data?.slides)) {
    data.slides.forEach((slide, index) => {
      const slideObj = pptx.addSlide();
      slideObj.background = { color: BG_COLOR };

      // Slide Header Title
      slideObj.addText(slide.title || `Slide ${index + 1}`, {
        x: 0.8,
        y: 0.6,
        w: 11.5,
        h: 0.8,
        fontSize: 26,
        fontFace: "Arial",
        bold: true,
        color: TEXT_MAIN,
      });

      // Subheader Border Line
      slideObj.addShape(pptx.shapes.LINE, {
        x: 0.8,
        y: 1.4,
        w: 11.7,
        h: 0,
        line: { color: "1E293B", width: 1.5 },
      });

      // 🔴 BUG FIX: Format each point into a clean pptxgenjs bullet object
      if (Array.isArray(slide.points) && slide.points.length > 0) {
        const formattedPoints = slide.points.map((pointText) => ({
          text: pointText,
          options: {
            bullet: true, // 👈 Ensures pptxgenjs natively renders standard bullets
            fontSize: 15,
            fontFace: "Arial",
            color: TEXT_MUTED,
            spaceAfter: 12,
          },
        }));

        // Render bullets in a single container
        slideObj.addText(formattedPoints, {
          x: 0.8,
          y: 1.8,
          w: 11.5,
          h: 4.8,
          valign: "top",
        });
      }

      // Slide Number Footer
      slideObj.addText(`${index + 1} / ${data.slides.length}`, {
        x: 11.5,
        y: 6.8,
        w: 1.0,
        h: 0.4,
        fontSize: 10,
        fontFace: "Arial",
        color: "64748B",
        align: "right",
      });
    });
  }

  // -------------------------------------------------------------
  // 3. Thank You Slide (Closing)
  // -------------------------------------------------------------
  const endSlide = pptx.addSlide();
  endSlide.background = { color: BG_COLOR };

  endSlide.addText("Thank You!", {
    x: 0.5,
    y: 2.8,
    w: 12.33,
    h: 1.2,
    fontSize: 48,
    fontFace: "Arial",
    bold: true,
    color: TEXT_MAIN,
    align: "center",
  });

  endSlide.addText("Generated by ElysiumAI", {
    x: 0.5,
    y: 4.0,
    w: 12.33,
    h: 0.5,
    fontSize: 16,
    fontFace: "Arial",
    color: ACCENT_COLOR,
    align: "center",
  });

  // Export as Node.js Buffer for S3
  return await pptx.write({ outputType: "nodebuffer" });
};
